//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int docId { get; set; }
        public string docName { get; set; }
        public string docDesc { get; set; }
        public int accessCount { get; set; }
        public int userId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
